# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vs-poc-web-app

on:
  push:
    branches:
      - approval-integration
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip

      - name: Vendor Python dependencies into repo
        run: |
          # Prefer wheels; if any package has no wheel, fall back to source build
          pip install --only-binary :all: --target ./py_deps -r req.txt || \
          pip install --target ./py_deps -r req.txt
          chmod -R a+rX py_deps

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          echo "Frontend built successfully"

      - name: Sanity check vendored imports
        run: |
          PYTHONPATH="$PWD/py_deps" python - << 'PY'
          import sys
          print("Python:", sys.version)
          print("PYTHONPATH ok?", any("py_deps" in p for p in sys.path))
          
          # Test critical imports
          import dotenv
          print("dotenv: imported successfully")
          
          import aiohttp
          print("aiohttp:", aiohttp.__version__)
          
          import requests
          print("requests:", requests.__version__)
          
          import dateutil
          print("dateutil:", dateutil.__version__)
          
          import msgraph
          print("msgraph: imported successfully")
          
          print("All imports successful!")
          PY

      - name: Build application
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Verify public folder exists
        run: |
          ls -la
          ls -la public/
          echo "Contents of public folder verified"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules
            !.git
            !.github

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vs-poc-web-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
